FargoWebApplication/FargoWebApplication/Controllers/DatabaseController.cs
using Fargo_Application.App_Start;
using FargoWebApplication.Filter;
using FargoWebApplication.Manager;
using System;
using System.Collections.Generic;
using System.Data.SqlClient;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FargoWebApplication.Controllers
{
    [UserAuthorization]
    public class DatabaseController : Controller
    {
        public ActionResult Index()
        {
            ViewBag.Message = null;
            return View();
        }

        [HttpPost]
        public ActionResult Index(string BackupPath)
        {
            int result = 0;
            try
            {
                string DatabaseName = "DbFargoApplication" + DateTime.Now.ToString("ddMMyyymmss") + ".Bak";
                BackupPath = Path.Combine(Server.MapPath("~/Database/Backup/"), DatabaseName);
                string newPath = @"G:\TBB\Fargo Application\Fargo application with new layout integration\Fargo web application\FargoWebApplication\FargoWebApplication\NewDatabase\NewBackup";
                result = DatabaseManager.Backup(newPath);
                ViewBag.Message = result;
            }
            catch (Exception exception)
            {
                ExceptionLogging.SendErrorToText(exception);
            }
            return View();
        }
    

    
        public ActionResult Backup()
        {
            return View();
        }
    
        [HttpPost]
        public ActionResult Backup(string BackupPath)
        {
            int result = 0;
            try
            {
                BackupPath = Server.MapPath("~/Database/Backup/");
                result= DatabaseManager.Backup(BackupPath);
            }
            catch (Exception exception)
            {
                ExceptionLogging.SendErrorToText(exception);
            }
            return View();
        }
    }
}

FargoWebApplication/FargoWebApplication/Views/Database/Backup.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<style type="text/css">
    #loader {
        background-color: transparent;
        background: transparent;
        display: none;
        position: fixed;
        top: 0;
        left: 0;
        right: 0;
        bottom: 0;
        background-image: url('../../Images/480px-Loader.gif');
        background-repeat: no-repeat;
        background-position: center;
        background-color: white;
        z-index: 10000;
    }

    .btn {
        background-color: #0a654d;
        border-color: #0a654d;
    }

        .btn:hover {
            background-color: #074434;
            border-color: #074434;
        }

        .btn:active {
            background-color: #0a654d !important;
            border-color: #0a654d;
        }

        .btn:focus {
            -webkit-box-shadow: none;
            box-shadow: none;
            color: #fff;
            background-color: #074434;
        }
</style>


<style>
    .fontDesign {
        color: #666666;
        font-weight: bold;
        font-size: 13px;
    }
</style>
@if (ViewBag.Message != null)
{
    <script>alert('@ViewBag.Message');</script>
}

<div class="main-body">
    <div class="page-wrapper">


        <div class="page-body">
            <div class="row">
                <div class="col-sm-12">
                    <div class="card">
                        <div class="card-block primary-breadcrumb" style="height:12px; background: linear-gradient(45deg, #074434, #0a654d);">
                            <div class="breadcrumb-header">
                                <h6><label style="color:white">Database Backup</label></h6>
                            </div>
                        </div>
                        <div class="card-block">
                            @using (Html.BeginForm("Backup", "Database", FormMethod.Post, new { enctype = "multipart/form-data", id = "frmDatabaseBackup" }))
                            {
                                <div class="row">
                                    <div class="col-md-12" align="center">
                                        <input type="submit" class="btn btn-success" id="btnBackup" value="Backup" name="Backup">
                                    </div>
                                </div>
                            }
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

</div>
<!-- Page-body end -->

<div id="loader" style="text-align:center; padding-top:20%;">
    <span style="font-size:22px;color:#dce3de;">Please wait...</span>
</div>
<div id="styleSelector">

</div>
<script type="text/javascript" src="~/Assets/js/jquery/jquery.min.js"></script>

FargoWebApplication/FargoWebApplication/Views/Database/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<style type="text/css">
    #loader {
        background-color: transparent;
        background: transparent;
        display: none;
        position: fixed;
        top: 0;
        left: 0;
        right: 0;
        bottom: 0;
        background-image: url('../../Images/480px-Loader.gif');
        background-repeat: no-repeat;
        background-position: center;
        background-color: white;
        z-index: 10000;
    }

    .btn {
        background-color: #0a654d;
        border-color: #0a654d;
    }

        .btn:hover {
            background-color: #074434;
            border-color: #074434;
        }

        .btn:active {
            background-color: #0a654d !important;
            border-color: #0a654d;
        }

        .btn:focus {
            -webkit-box-shadow: none;
            box-shadow: none;
            color: #fff;
            background-color: #074434;
        }
</style>


<style>
    .fontDesign {
        color: #666666;
        font-weight: bold;
        font-size: 13px;
    }
</style>
@if (ViewBag.Message != null)
{
    <script>alert('@ViewBag.Message');</script>
}

<div class="main-body">
    <div class="page-wrapper">


        <div class="page-body">
            <div class="row">
                <div class="col-sm-12">
                    <div class="card">
                        <div class="card-block primary-breadcrumb" style="height:12px; background: linear-gradient(45deg, #074434, #0a654d);">
                            <div class="breadcrumb-header">
                                <h6><label style="color:white">Database Backup</label></h6>
                            </div>
                        </div>
                        <div class="card-block">
                            @using (Html.BeginForm("Index", "Database", FormMethod.Post, new { enctype = "multipart/form-data", id = "frmDatabaseBackup" }))
                            {
                                <div class="row">
                                    <div class="col-md-12" align="center">
                                        <input type="submit" class="btn btn-success" id="btnBackup" value="Backup" name="Backup">
                                    </div>
                                </div>
                            }
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

</div>
<!-- Page-body end -->

<div id="loader" style="text-align:center; padding-top:20%;">
    <span style="font-size:22px;color:#dce3de;">Please wait...</span>
</div>
<div id="styleSelector">

</div>
<script type="text/javascript" src="~/Assets/js/jquery/jquery.min.js"></script>